import streamlit as st

from ai.watchlist import (
    generate_watchlist,
    get_watchlist_table
)


def render():
    st.info(
    """
    This watchlist ranks stocks using:

    • RSI
    • MACD
    • Trend Strength
    • Proprietary Alpha Score

    Higher score = Better opportunity.
    """
    )

    st.header("🔥 AI Watchlist")

    st.caption(
        "Top-ranked opportunities generated by AlphaLensAI."
    )

    if st.button(
        "Generate Watchlist"
    ):

        table = get_watchlist_table()
        top_stock = table.iloc[0]

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "🥇 Top Stock",
                top_stock["ticker"]
            )

        with col2:
            st.metric(
                "Alpha Score",
                round(top_stock["score"], 2)
            )

        with col3:
            st.metric(
                "RSI",
                round(top_stock["rsi"], 2)
            )

        st.subheader(
            "📊 Top Ranked Stocks"
        )
        table["recommendation"] = table["score"].apply(
            lambda x:
            "STRONG BUY" if x >= 80
            else "BUY" if x >= 65
            else "HOLD" if x >= 50
            else "AVOID"
        )

        display_table = table[
            [
                "ticker",
                "sector",
                "score",
                "trend",
                "risk",
                "recommendation"
            ]
        ]

        st.dataframe(
            display_table.style.highlight_max(
                subset=["score"],
                color="#1f6f43"
            ),
            use_container_width=True
        )
        st.markdown("---")

        st.subheader("🎯 Top Opportunities")

        for _, row in table.head(3).iterrows():

            st.success(
                f"""
                {row['ticker']}

                Score: {row['score']:.2f}

                Recommendation: {row['recommendation']}
                """
            )

        st.markdown("---")

        with st.spinner(
            "Generating AI Commentary..."
        ):

            try:
                report = generate_watchlist()

            except Exception:
                report = """
            AI analysis currently unavailable.

            Technical indicators, rankings and portfolio analytics remain fully operational.
            """

            with st.expander(
                "🤖 AI Commentary",
                expanded=True
            ):

                st.markdown(report)
                st.success(
"Top-ranked stock is considered today's strongest opportunity."
)